package com.samayahr.dto.response;

import com.samayahr.entity.PayrollHistory;
import com.samayahr.entity.PayrollHistory.PayrollStatus;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class PayrollResponse {
    private Long id;
    private Long userId;
    private String userName;
    private String employeeId;
    private String employeeName;
    private LocalDateTime joiningDate;
    private String dateOfJoining;
    private String department;
    private String designation;
    private String tenantCode;
    private Long companyId;
    private String companyName;
    private LocalDate payrollMonth;
    private BigDecimal basicSalary;
    private BigDecimal hra;
    private BigDecimal specialAllowance;
    private BigDecimal conveyanceAllowance;
    private BigDecimal medicalAllowance;
    private BigDecimal lta;
    private BigDecimal otherAllowances;
    private BigDecimal totalEarnings;
    private BigDecimal pfEmployee;
    private BigDecimal esiEmployee;
    private BigDecimal professionalTax;
    private BigDecimal taxDeductions;
    private BigDecimal otherDeductions;
    private BigDecimal totalDeductions;
    private BigDecimal netSalary;
    private Integer lopDays;
    private Integer overtimeHours;
    private PayrollHistory.PayrollStatus status;
    private LocalDate paymentDate;
    private Boolean payslipGenerated;
    private String payslipPath;
    private Boolean autoGenerated;
    private String remarks;
    private LocalDateTime createdAt;
    private String source;
    private String payPeriod;
    private String payDate;
    private Integer workingDays;
    private Integer paidDays;
    private String bankName;
    private String accountNumber;
    private String ifscCode;
    private String branchName;
    private String panNumber;
    private String uanNumber;
    private String pfNumber;
    private String esiNumber;
    private List<PayrollItemResponse> earnings;
    private List<PayrollItemResponse> deductions;
    
    
    

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getUserId() {
		return userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}
	public String getEmployeeName() {
		return employeeName;
	}
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	public LocalDateTime getJoiningDate() {
		return joiningDate;
	}
	public void setJoiningDate(LocalDateTime joiningDate) {
		this.joiningDate = joiningDate;
	}
	public String getDateOfJoining() {
		return dateOfJoining;
	}
	public void setDateOfJoining(String dateOfJoining) {
		this.dateOfJoining = dateOfJoining;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public String getDesignation() {
		return designation;
	}
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	public String getTenantCode() {
		return tenantCode;
	}
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}
	public Long getCompanyId() {
		return companyId;
	}
	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public LocalDate getPayrollMonth() {
		return payrollMonth;
	}
	public void setPayrollMonth(LocalDate payrollMonth) {
		this.payrollMonth = payrollMonth;
	}
	public BigDecimal getBasicSalary() {
		return basicSalary;
	}
	public void setBasicSalary(BigDecimal basicSalary) {
		this.basicSalary = basicSalary;
	}
	public BigDecimal getHra() {
		return hra;
	}
	public void setHra(BigDecimal hra) {
		this.hra = hra;
	}
	public BigDecimal getSpecialAllowance() {
		return specialAllowance;
	}
	public void setSpecialAllowance(BigDecimal specialAllowance) {
		this.specialAllowance = specialAllowance;
	}
	public BigDecimal getConveyanceAllowance() {
		return conveyanceAllowance;
	}
	public void setConveyanceAllowance(BigDecimal conveyanceAllowance) {
		this.conveyanceAllowance = conveyanceAllowance;
	}
	public BigDecimal getMedicalAllowance() {
		return medicalAllowance;
	}
	public void setMedicalAllowance(BigDecimal medicalAllowance) {
		this.medicalAllowance = medicalAllowance;
	}
	public BigDecimal getLta() {
		return lta;
	}
	public void setLta(BigDecimal lta) {
		this.lta = lta;
	}
	public BigDecimal getOtherAllowances() {
		return otherAllowances;
	}
	public void setOtherAllowances(BigDecimal otherAllowances) {
		this.otherAllowances = otherAllowances;
	}
	public BigDecimal getTotalEarnings() {
		return totalEarnings;
	}
	public void setTotalEarnings(BigDecimal totalEarnings) {
		this.totalEarnings = totalEarnings;
	}
	public BigDecimal getPfEmployee() {
		return pfEmployee;
	}
	public void setPfEmployee(BigDecimal pfEmployee) {
		this.pfEmployee = pfEmployee;
	}
	public BigDecimal getEsiEmployee() {
		return esiEmployee;
	}
	public void setEsiEmployee(BigDecimal esiEmployee) {
		this.esiEmployee = esiEmployee;
	}
	public BigDecimal getProfessionalTax() {
		return professionalTax;
	}
	public void setProfessionalTax(BigDecimal professionalTax) {
		this.professionalTax = professionalTax;
	}
	public BigDecimal getTaxDeductions() {
		return taxDeductions;
	}
	public void setTaxDeductions(BigDecimal taxDeductions) {
		this.taxDeductions = taxDeductions;
	}
	public BigDecimal getOtherDeductions() {
		return otherDeductions;
	}
	public void setOtherDeductions(BigDecimal otherDeductions) {
		this.otherDeductions = otherDeductions;
	}
	public BigDecimal getTotalDeductions() {
		return totalDeductions;
	}
	public void setTotalDeductions(BigDecimal totalDeductions) {
		this.totalDeductions = totalDeductions;
	}
	public BigDecimal getNetSalary() {
		return netSalary;
	}
	public void setNetSalary(BigDecimal netSalary) {
		this.netSalary = netSalary;
	}
	public Integer getLopDays() {
		return lopDays;
	}
	public void setLopDays(Integer lopDays) {
		this.lopDays = lopDays;
	}
	public Integer getOvertimeHours() {
		return overtimeHours;
	}
	public void setOvertimeHours(Integer overtimeHours) {
		this.overtimeHours = overtimeHours;
	}
	public PayrollHistory.PayrollStatus getStatus() {
		return status;
	}
	public void setStatus(PayrollHistory.PayrollStatus status) {
		this.status = status;
	}
	public LocalDate getPaymentDate() {
		return paymentDate;
	}
	public void setPaymentDate(LocalDate paymentDate) {
		this.paymentDate = paymentDate;
	}
	public Boolean getPayslipGenerated() {
		return payslipGenerated;
	}
	public void setPayslipGenerated(Boolean payslipGenerated) {
		this.payslipGenerated = payslipGenerated;
	}
	public String getPayslipPath() {
		return payslipPath;
	}
	public void setPayslipPath(String payslipPath) {
		this.payslipPath = payslipPath;
	}
	public Boolean getAutoGenerated() {
		return autoGenerated;
	}
	public void setAutoGenerated(Boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public LocalDateTime getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}
	public String getSource() {
		return source;
	}
	public void setSource(String source) {
		this.source = source;
	}
	public String getPayPeriod() {
		return payPeriod;
	}
	public void setPayPeriod(String payPeriod) {
		this.payPeriod = payPeriod;
	}
	public String getPayDate() {
		return payDate;
	}
	public void setPayDate(String payDate) {
		this.payDate = payDate;
	}
	public Integer getWorkingDays() {
		return workingDays;
	}
	public void setWorkingDays(Integer workingDays) {
		this.workingDays = workingDays;
	}
	public Integer getPaidDays() {
		return paidDays;
	}
	public void setPaidDays(Integer paidDays) {
		this.paidDays = paidDays;
	}
	public String getBankName() {
		return bankName;
	}
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
	public String getAccountNumber() {
		return accountNumber;
	}
	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}
	public String getIfscCode() {
		return ifscCode;
	}
	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}
	public String getBranchName() {
		return branchName;
	}
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}
	public String getPanNumber() {
		return panNumber;
	}
	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}
	public String getUanNumber() {
		return uanNumber;
	}
	public void setUanNumber(String uanNumber) {
		this.uanNumber = uanNumber;
	}
	public String getPfNumber() {
		return pfNumber;
	}
	public void setPfNumber(String pfNumber) {
		this.pfNumber = pfNumber;
	}
	public String getEsiNumber() {
		return esiNumber;
	}
	public void setEsiNumber(String esiNumber) {
		this.esiNumber = esiNumber;
	}
	public List<PayrollItemResponse> getEarnings() {
		return earnings;
	}
	public void setEarnings(List<PayrollItemResponse> earnings) {
		this.earnings = earnings;
	}
	public List<PayrollItemResponse> getDeductions() {
		return deductions;
	}
	public void setDeductions(List<PayrollItemResponse> deductions) {
		this.deductions = deductions;
	}
    
    
    
    
}
