import React, { useState, useEffect, useCallback, useMemo } from "react";
import {
  Eye,
  Edit,
  Search,
  ArrowLeft,
  RefreshCw,
  Plus,
  FileText,
  Loader2,
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import api from "@/lib/apiClient";

const PayoutsOperations = ({ onBack }) => {
  const navigate = useNavigate();
  
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedStatus, setSelectedStatus] = useState("All Status");
  const [selectedMonth, setSelectedMonth] = useState("All Months");
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState("");
  const [actionLoading, setActionLoading] = useState({});
  const [detailRecord, setDetailRecord] = useState(null);

  // 🌟 BACKEND DATA
  const [payrollRecords, setPayoutsRecords] = useState([]);

  // ✅ FIXED: Robust fetch with proper error handling
  const fetchPayoutsRecords = useCallback(async () => {
    try {
      setLoading(true);
      setLoadError("");

      const res = await api.get("/api/payroll");

      const data = res.data;
      console.log("✅ Raw data:", data);

      // ✅ Handle ALL possible backend response shapes
      let records = [];
      if (Array.isArray(data)) {
        records = data;
      } else if (Array.isArray(data.data)) {
        records = data.data;
      } else if (Array.isArray(data.payrolls)) {
        records = data.payrolls;
      } else if (Array.isArray(data.records)) {
        records = data.records;
      } else if (data.content && Array.isArray(data.content)) {
        records = data.content;
      }

      // ✅ Normalize numeric fields (backend might send strings)
      const normalizedRecords = records.map(record => ({
        ...record,
        userId: record.userId || record.user_id,
        userName: record.userName || record.username || record.user_name || record.name || "Unknown",
        employeeId: record.employeeId || record.employee_id || `EMP-${record.userId}`,
        employeeName: record.employeeName || record.employee_name || record.userName || "Unknown",
        joiningDate: record.joiningDate || record.joining_date,
        basicCompensation: Number(record.basicCompensation || record.basic_salary || 0),
        totalEarnings: Number(record.totalEarnings || record.total_earnings || 0),
        totalDeductions: Number(record.totalDeductions || record.total_deductions || 0),
        netCompensation: Number(record.netCompensation || record.net_salary || 0),
        lopDays: Number(record.lopDays || record.lop_days || 0),
        payrollMonth: record.payrollMonth || record.payroll_month,
        autoGenerated: Boolean(record.autoGenerated || record.auto_generated || false),
        source: record.source || (record.autoGenerated ? "Auto Generated" : "Direct Entry"),
      }));

      console.log("📊 Normalized records:", normalizedRecords.length);
      setPayoutsRecords(normalizedRecords);

    } catch (error) {
      console.error("❌ Fetch payroll error:", error);
      setLoadError(error.message || "Failed to load payroll records.");
    } finally {
      setLoading(false);
    }
  }, []);

  // ✅ Load data on mount
  useEffect(() => {
    fetchPayoutsRecords();
  }, [fetchPayoutsRecords]);

  // ✅ Client-side filtering (until backend supports query params)
  const filteredRecords = useMemo(() => {
    return payrollRecords.filter(record => {
      const matchesSearch = !searchTerm || 
        record.employeeName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        record.userName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        record.employeeId?.toString().includes(searchTerm) ||
        record.userId?.toString().includes(searchTerm);

      const matchesStatus = selectedStatus === "All Status" || 
        (selectedStatus === "Pending" && !record.status) ||
        record.status === selectedStatus;

      const matchesMonth = selectedMonth === "All Months" || 
        record.payrollMonth?.includes(selectedMonth.split(' ')[0]);

      return matchesSearch && matchesStatus && matchesMonth;
    });
  }, [payrollRecords, searchTerm, selectedStatus, selectedMonth]);

  const formatDate = (dateStr) => {
    if (!dateStr) return "N/A";
    try {
      const date = new Date(dateStr);
      return date.toLocaleDateString('en-IN', { 
        year: 'numeric', 
        month: 'short' 
      });
    } catch {
      return dateStr;
    }
  };

  const formatJoiningDate = (dateStr) => {
    if (!dateStr) return "N/A";
    try {
      const date = new Date(dateStr);
      return date.toLocaleDateString('en-IN', { 
        year: 'numeric', 
        month: 'short',
        day: 'numeric'
      });
    } catch {
      return dateStr;
    }
  };

  const getStatusBadge = (status) => {
    const s = (status || "PENDING").toUpperCase();
    const map = {
      PENDING:   { bg: "#fef9c3", color: "#854d0e", border: "#fde68a" },
      APPROVED:  { bg: "#dcfce7", color: "#166534", border: "#bbf7d0" },
      PAID:      { bg: "#fff7ed", color: "#c2410c", border: "#fed7aa" },
      CANCELLED: { bg: "#fee2e2", color: "#991b1b", border: "#fecaca" },
      LOCKED:    { bg: "#f1f5f9", color: "#475569", border: "#cbd5e1" },
    };
    const cfg = map[s] || map.PENDING;
    return {
      display: "inline-flex", borderRadius: 20, padding: "3px 10px",
      fontSize: 11, fontWeight: 700, letterSpacing: "0.03em",
      background: cfg.bg, color: cfg.color, border: `1px solid ${cfg.border}`,
    };
  };

  const handleManualEntry = () => {
    navigate("/admin/manual-payroll-entry");
  };

  const handleViewDetails = (record) => {
    setDetailRecord(record);
  };

  const handleEdit = (record) => {
    alert(`Edit functionality for ${record.employeeName} will be implemented soon.`);
  };

  // ── Payouts workflow actions ──────────────────────────────────────────────
  const doAction = useCallback(async (id, action) => {
    setActionLoading(prev => ({ ...prev, [`${id}_${action}`]: true }));
    try {
      const res = await api.patch(`/api/payroll/${id}/${action}`);
      const data = res.data;
      // Update record in list
      setPayoutsRecords(prev => prev.map(r =>
        r.id === id ? { ...r, status: data.data?.status || r.status, isLocked: data.data?.isLocked ?? r.isLocked } : r
      ));
    } catch (err) {
      alert(`${action} failed: ${err.message}`);
    } finally {
      setActionLoading(prev => ({ ...prev, [`${id}_${action}`]: false }));
    }
  }, []);

  const handleGeneratePayStatement = useCallback(async (id) => {
    setActionLoading(prev => ({ ...prev, [`${id}_payslip`]: true }));
    try {
      const res = await api.post(`/api/payroll/${id}/generate-payslip`);
      const data = res.data;
      if (data.data?.payslipUrl) window.open(data.data.payslipUrl, "_blank");
      setPayoutsRecords(prev => prev.map(r =>
        r.id === id ? { ...r, payslipGenerated: true, payslipPath: data.data?.payslipUrl } : r
      ));
    } catch (err) {
      alert(`PayStatement error: ${err.message}`);
    } finally {
      setActionLoading(prev => ({ ...prev, [`${id}_payslip`]: false }));
    }
  }, []);

  return (
    <div className="w-full h-full bg-[#F9FAFF] p-6">
      

      {/* Header */}
      <div className="mb-6 flex flex-col justify-between gap-4 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm lg:flex-row lg:items-center">
        <div>
          {/* Back Button */}
         <button
        className="flex items-center gap-2 text-[#0f172a] text-sm font-medium"
        onClick={() => navigate("/admin/finance")}
      >
        <ArrowLeft size={18} /> Back to MoneyOps ControlRoom
      </button>
          <h1 className="text-2xl font-semibold text-[#0f172a] pt-2">
            Payout Control
          </h1>
          <p className="text-sm text-gray-500">
            Manage all payroll records ({filteredRecords.length} shown)
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <button
            onClick={fetchPayoutsRecords}
            disabled={loading}
            className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm transition hover:bg-gray-50 disabled:opacity-50"
          >
            <RefreshCw size={18} className={loading ? "animate-spin" : ""} />
            <span>{loading ? "Refreshing..." : "Refresh"}</span>
          </button>

          <button
            onClick={handleManualEntry}
            className="inline-flex items-center gap-2 rounded-xl bg-[#0f172a] px-4 py-2 text-sm font-medium text-white shadow-sm transition hover:bg-[#020f5d]"
          >
            <Plus size={18} />
            <span>Direct Entry</span>
          </button>

          <button
            onClick={() => alert("Export feature coming soon...")}
            className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm transition hover:bg-gray-50"
          >
            <FileText size={18} />
            <span>Export</span>
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="mb-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
        <div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          {/* Search */}
          <div className="relative w-full max-w-md">
            <Search
              className="pointer-events-none absolute left-3 top-2.5 text-gray-400"
              size={18}
            />
            <input
              type="text"
              placeholder="Search by employee name or ID..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full rounded-xl border border-gray-200 bg-[#F9FAFF] py-2.5 pl-10 pr-4 text-sm text-gray-800 placeholder:text-gray-400 focus:border-[#0f172a] focus:outline-none focus:ring-2 focus:ring-[#0f172a]/20"
            />
          </div>

          {/* Quick Filters */}
          <div className="flex gap-3">
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="rounded-xl border border-gray-200 bg-[#F9FAFF] px-4 py-2.5 text-sm text-gray-700 focus:border-[#0f172a] focus:outline-none focus:ring-2 focus:ring-[#0f172a]/20"
            >
              <option>All Status</option>
              <option value="PENDING">Pending</option>
              <option value="APPROVED">Approved</option>
              <option value="PAID">Paid</option>
              <option value="LOCKED">Locked</option>
              <option value="CANCELLED">Cancelled</option>
            </select>
            
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="rounded-xl border border-gray-200 bg-[#F9FAFF] px-4 py-2.5 text-sm text-gray-700 focus:border-[#0f172a] focus:outline-none focus:ring-2 focus:ring-[#0f172a]/20"
            >
              <option>All Months</option>
              {(() => {
                const months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
                const currentYear = new Date().getFullYear();
                const opts = [];
                for (let y = currentYear; y >= currentYear - 2; y--) {
                  months.forEach(m => opts.push(`${m} ${y}`));
                }
                return opts.map(o => <option key={o}>{o}</option>);
              })()}
            </select>
          </div>
        </div>
      </div>

      {/* Records Table */}
      <div className="rounded-2xl border border-gray-200 bg-white shadow-sm">
        <div className="px-6 py-4 border-[#8B5CF6] border-gray-100">
          <h2 className="text-lg font-semibold text-[#0f172a]">
            Payouts Records ({filteredRecords.length})
          </h2>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gradient-to-r from-[#EEF0FF] to-[#E0E7FF]">
              <tr>
                <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Person
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Person ID
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Joining Date
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Month
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Source
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Basic Compensation
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Total Earnings
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Deductions
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Net Compensation
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Status
                </th>
                <th className="px-4 py-4 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  LOP Days
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 bg-white">
              {loading ? (
                <tr>
                  <td colSpan={12} className="px-6 py-12 text-center">
                    <Loader2 className="mx-auto h-8 w-8 animate-spin text-[#0f172a]" />
                    <p className="mt-2 text-sm text-gray-500">Loading payroll records...</p>
                  </td>
                </tr>
              ) : loadError ? (
                <tr>
                  <td colSpan={12} className="px-6 py-12 text-center">
                    <p className="text-sm font-medium text-red-600">{loadError}</p>
                    <button
                      onClick={fetchPayoutsRecords}
                      className="mt-2 rounded-lg bg-red-50 px-4 py-2 text-sm text-red-700 hover:bg-red-100"
                    >
                      Retry
                    </button>
                  </td>
                </tr>
              ) : filteredRecords.length === 0 ? (
                <tr>
                  <td colSpan={12} className="px-6 py-12 text-center">
                    <FileText className="mx-auto h-12 w-12 text-gray-400" />
                    <p className="mt-2 text-sm font-medium text-gray-900">No payroll records found</p>
                    <p className="text-sm text-gray-500">
                      {searchTerm ? "Try adjusting your search" : "No records match your filters"}
                    </p>
                  </td>
                </tr>
              ) : (
                filteredRecords.map((record, index) => (
                  <tr key={record.id || index} className="hover:bg-gray-50">
                    <td className="px-6 py-4">
                      <div className="flex flex-col">
                        <span className="text-sm font-semibold text-gray-900">
                          {record.employeeName || record.userName || "Unknown"}
                        </span>
                      </div>
                    </td>
                    <td className="px-4 py-4">
                      <span className="text-sm font-mono text-gray-700">
                        {record.employeeId}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span className="text-sm text-gray-700">
                        {formatJoiningDate(record.joiningDate)}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span className="text-sm text-gray-900">
                        {formatDate(record.payrollMonth)}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                        record.autoGenerated 
                          ? 'bg-green-100 text-green-800' 
                          : 'bg-orange-100 text-[#8B5CF6]lue-800'
                      }`}>
                        {record.autoGenerated ? "Auto" : "Manual"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-mono text-gray-900">
                        ₹{record.basicCompensation?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-mono text-gray-900">
                        ₹{record.totalEarnings?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-mono text-gray-900">
                        ₹{record.totalDeductions?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm font-bold text-emerald-600">
                        ₹{record.netCompensation?.toLocaleString("en-IN") || "0"}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <span style={getStatusBadge(record.status)}>
                        {(record.status || "PENDING").toUpperCase()}
                        {record.isLocked && " 🔒"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <span className="text-sm text-gray-900">{record.lopDays || 0}</span>
                    </td>
                    <td className="px-4 py-4">
                      <div className="flex items-center gap-1 flex-wrap">
                        {/* View */}
                        <button onClick={() => handleViewDetails(record)} title="View Details"
                          className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-500 hover:bg-indigo-50 hover:text-indigo-600 transition">
                          <Eye size={14} />
                        </button>

                        {/* Approve — only for PENDING */}
                        {(record.status === "PENDING" || record.status === "Pending" || !record.status) && (
                          <button
                            onClick={() => doAction(record.id, "approve")}
                            disabled={actionLoading[`${record.id}_approve`]}
                            title="Approve"
                            className="inline-flex h-8 px-2 items-center gap-1 rounded-lg border border-green-200 bg-green-50 text-green-700 text-xs font-semibold hover:bg-green-100 transition disabled:opacity-50"
                          >
                            {actionLoading[`${record.id}_approve`]
                              ? <Loader2 size={12} className="animate-spin" />
                              : "✓ Approve"}
                          </button>
                        )}

                        {/* Mark Paid — only for APPROVED */}
                        {(record.status === "APPROVED" || record.status === "Approved") && (
                          <button
                            onClick={() => doAction(record.id, "pay")}
                            disabled={actionLoading[`${record.id}_pay`]}
                            title="Mark as Paid"
                            className="inline-flex h-8 px-2 items-center gap-1 rounded-lg border border-orange-200 bg-orange-50 text-orange-700 text-xs font-semibold hover:bg-orange-100 transition disabled:opacity-50"
                          >
                            {actionLoading[`${record.id}_pay`]
                              ? <Loader2 size={12} className="animate-spin" />
                              : "₹ Pay"}
                          </button>
                        )}

                        {/* Lock — for APPROVED or PAID */}
                        {!record.isLocked && (record.status === "APPROVED" || record.status === "Approved" || record.status === "PAID" || record.status === "Paid") && (
                          <button
                            onClick={() => doAction(record.id, "lock")}
                            disabled={actionLoading[`${record.id}_lock`]}
                            title="Lock (finalise)"
                            className="inline-flex h-8 px-2 items-center gap-1 rounded-lg border border-gray-200 bg-gray-50 text-gray-600 text-xs font-semibold hover:bg-gray-100 transition disabled:opacity-50"
                          >
                            {actionLoading[`${record.id}_lock`]
                              ? <Loader2 size={12} className="animate-spin" />
                              : "🔒 Lock"}
                          </button>
                        )}

                        {/* Generate PayStatement */}
                        {!record.payslipGenerated && (record.status === "APPROVED" || record.status === "Approved" || record.status === "PAID" || record.status === "Paid") && (
                          <button
                            onClick={() => handleGeneratePayStatement(record.id)}
                            disabled={actionLoading[`${record.id}_payslip`]}
                            title="Generate PayStatement PDF"
                            className="inline-flex h-8 px-2 items-center gap-1 rounded-lg border border-blue-200 bg-violet-50 text-blue-700 text-xs font-semibold hover:bg-blue-100 transition disabled:opacity-50"
                          >
                            {actionLoading[`${record.id}_payslip`]
                              ? <Loader2 size={12} className="animate-spin" />
                              : "📄 Slip"}
                          </button>
                        )}

                        {/* Download if payslip exists */}
                        {record.payslipPath && (
                          <a href={record.payslipPath} target="_blank" rel="noopener noreferrer"
                            title="Download PayStatement"
                            className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-[#8B5CF6]/30 bg-orange-50 text-[#8B5CF6] hover:bg-orange-100 transition">
                            <FileText size={13} />
                          </a>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ── Detail Modal ─────────────────────────────────────────────────── */}
      {detailRecord && (
        <div style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.45)", zIndex:1000, display:"flex", alignItems:"center", justifyContent:"center", padding:16 }}
          onClick={() => setDetailRecord(null)}>
          <div style={{ background:"#fff", borderRadius:18, width:"100%", maxWidth:560, maxHeight:"90vh", overflowY:"auto", padding:"28px 30px" }}
            onClick={e => e.stopPropagation()}>
            <div style={{ display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:20 }}>
              <div>
                <p style={{ fontSize:11, fontWeight:700, color:"#94a3b8", textTransform:"uppercase", letterSpacing:"0.08em", margin:0 }}>Payouts Detail</p>
                <p style={{ fontSize:18, fontWeight:800, color:"#0f172a", margin:"4px 0 0" }}>
                  {detailRecord.employeeName || detailRecord.userName}
                </p>
              </div>
              <button onClick={() => setDetailRecord(null)}
                style={{ width:32, height:32, borderRadius:"50%", border:"1px solid #e2e8f0", background:"#f8fafc", cursor:"pointer", display:"flex", alignItems:"center", justifyContent:"center", fontSize:16 }}>
                ×
              </button>
            </div>

            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10 }}>
              {[
                ["Person ID", detailRecord.employeeId],
                ["Month", detailRecord.payrollMonth],
                ["Department", detailRecord.department || "—"],
                ["Designation", detailRecord.designation || "—"],
                ["Status", (detailRecord.status || "PENDING").toUpperCase()],
                ["LOP Days", detailRecord.lopDays || 0],
                ["Working Days", detailRecord.workingDays || "—"],
                ["Source", detailRecord.source || "—"],
              ].map(([label, val]) => (
                <div key={label} style={{ background:"#f8fafc", borderRadius:10, padding:"10px 14px" }}>
                  <p style={{ fontSize:10, fontWeight:700, color:"#94a3b8", textTransform:"uppercase", margin:0 }}>{label}</p>
                  <p style={{ fontSize:13, fontWeight:600, color:"#1e293b", margin:"3px 0 0" }}>{val}</p>
                </div>
              ))}
            </div>

            <div style={{ marginTop:16, display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:10 }}>
              {[
                ["Total Earnings", detailRecord.totalEarnings, "#16a34a"],
                ["Total Deductions", detailRecord.totalDeductions, "#dc2626"],
                ["Net Compensation", detailRecord.netCompensation, "#0B1020"],
              ].map(([label, val, color]) => (
                <div key={label} style={{ background:"#f8fafc", borderRadius:10, padding:"12px 14px", textAlign:"center" }}>
                  <p style={{ fontSize:10, fontWeight:700, color:"#94a3b8", textTransform:"uppercase", margin:0 }}>{label}</p>
                  <p style={{ fontSize:16, fontWeight:900, color, margin:"4px 0 0" }}>
                    ₹{Number(val || 0).toLocaleString("en-IN")}
                  </p>
                </div>
              ))}
            </div>

            {/* Dynamic earnings/deductions if present */}
            {(Array.isArray(detailRecord.earnings) && detailRecord.earnings.length > 0) && (
              <div style={{ marginTop:16 }}>
                <p style={{ fontSize:11, fontWeight:700, color:"#16a34a", textTransform:"uppercase", letterSpacing:"0.07em", marginBottom:8 }}>Earnings Breakdown</p>
                {detailRecord.earnings.map((e, i) => (
                  <div key={i} style={{ display:"flex", justifyContent:"space-between", padding:"5px 0", borderBottom:"1px solid #f1f5f9" }}>
                    <span style={{ fontSize:12, color:"#334155" }}>{e.name || e.componentName}</span>
                    <span style={{ fontSize:12, fontWeight:700, color:"#16a34a" }}>₹{Number(e.amount||0).toLocaleString("en-IN")}</span>
                  </div>
                ))}
              </div>
            )}
            {(Array.isArray(detailRecord.deductions) && detailRecord.deductions.length > 0) && (
              <div style={{ marginTop:12 }}>
                <p style={{ fontSize:11, fontWeight:700, color:"#dc2626", textTransform:"uppercase", letterSpacing:"0.07em", marginBottom:8 }}>Deductions Breakdown</p>
                {detailRecord.deductions.map((d, i) => (
                  <div key={i} style={{ display:"flex", justifyContent:"space-between", padding:"5px 0", borderBottom:"1px solid #f1f5f9" }}>
                    <span style={{ fontSize:12, color:"#334155" }}>{d.name || d.componentName}</span>
                    <span style={{ fontSize:12, fontWeight:700, color:"#dc2626" }}>₹{Number(d.amount||0).toLocaleString("en-IN")}</span>
                  </div>
                ))}
              </div>
            )}

            {detailRecord.remarks && (
              <div style={{ marginTop:14, background:"#f8fafc", borderRadius:10, padding:"10px 14px" }}>
                <p style={{ fontSize:10, fontWeight:700, color:"#94a3b8", textTransform:"uppercase", margin:"0 0 4px" }}>Remarks</p>
                <p style={{ fontSize:12, color:"#475569", margin:0 }}>{detailRecord.remarks}</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default PayoutsOperations;
